# name：应用或包名称。
name: ycflutter
# description: 应用或包的描述、简介。
description: A new Flutter application.
# version：应用或包的版本号。
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

# dependencies：应用或包依赖的其它包或插件。
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: "^0.1.2"
  http: '>=0.11.3+12'
  flutter_webview_plugin: "^0.3.0+2"
  shared_preferences: "^0.4.1"
  json_serializable: "^2.0.0"
  json_annotation: "^2.0.0"
  build_runner: "^1.0.0"
  json_model: "^0.0.2"
  pull_to_refresh: "^1.4.0"
  dio: "^3.0.9"
  cached_network_image: "^2.5.1"

# dev_dependencies：开发环境依赖的工具包（而不是flutter应用本身依赖的包）。
dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter：flutter相关的配置选项。
flutter:
  uses-material-design: true
  assets:
  - lib/image/ic_launcher_round.png
  - lib/image/zhy.jpg
  - lib/image/ic_person.jpg
  - lib/image/image1.jpg
  - lib/image/image2.jpg
  - lib/image/image3.jpg
  - lib/image/image4.jpg
  - lib/image/image5.png
  - lib/image/jt.png











